version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "mysite/manage.py makemigrations && mysite/manage.py migrate && python mysite/manage.py runserver 0.0.0.0:8000"
    restart: always

#    command: python mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - django:/django

    ports:
      - 8000:8000
    env_file:
      - .env
volumes:
  django: